### ISSUE TITLE
Disable output in adl

### ISSUE THREAD

**Issue by pol2095** [adobe-flash/crossbridge#72]
Hello,

is-it possible to remove this output in adl ?

```
CModule::startAsync
         console: [object MyClass]
         args: null
         env: null
         preserveStack: true
         isAutoSetRealThreadId: true
CModule::start
         console: [object MyClass]
         args:
         env:
         preserveStack: true
CModule::dispose
```

Thanks
